DDLs for tables
Bosco28/EventFinder pull request #2
Opened 2020-04-05 23:27 UTC by dumbapple

2020-04-05 23:34 UTC, Bosco28 requested changes
Can you also add Inder's INSERT statements to this file? Thanks!

2020-04-05 23:34 UTC, Bosco28 commented on EventFinder-DDLs.sql
> +    FOREIGN KEY (DateOfBirth) REFERENCES DoB(DateOfBirth) ON DELETE CASCADE ON UPDATE CASCADE
Let's do `ON DELETE NO ACTION` instead of `ON DELETE CASCADE`

2020-04-05 23:34 UTC, Bosco28 commented on EventFinder-DDLs.sql
> +    OrganizerUserID INT PRIMARY KEY AUTO_INCREMENT,
This is also a foreign key referring to the user table. Therefore we don't need `AUTO_INCREMENT` here.

2020-04-05 23:34 UTC, Bosco28 commented on EventFinder-DDLs.sql
> +    FOREIGN KEY (OrganizerUserID) REFERENCES Organizer(OrganizerUserID) ON DELETE CASCADE
Let's do `ON DELETE NO ACTION` here

2020-04-06 03:49 UTC, Bosco28 requested changes

2020-04-06 03:49 UTC, Bosco28 commented on EventFinder-DDLs.sql
> +);
Move `Location` to come before `Event` otherwise there will be a foreign key error.

2020-04-06 03:49 UTC, Bosco28 commented on EventFinder-DDLs.sql
> +CREATE TABLE DoB (
Can you also add drop table queries here? Thanks!

2020-04-06 03:49 UTC, dumbapple commented
Btw the insert statements have to be in the order they appear in or it might fail due to foreign key constraints

2020-04-06 04:06 UTC, Bosco28 requested changes

2020-04-06 04:06 UTC, Bosco28 commented on EventFinder-DDLs.sql
> +    Name VARCHAR(200) NOT NULL
Location does not have name anymore. Let's just completely remove the location table and all its foreign keys.

2020-04-06 04:06 UTC, Bosco28 commented on EventFinder-DDLs.sql
> +CREATE TABLE DoB (
Let's remove the DoB table. We don't really need it anymore.

2020-04-06 04:28 UTC, Bosco28 requested changes

2020-04-06 04:28 UTC, Bosco28 commented on EventFinder-DDLs.sql
> +INSERT INTO Event VALUES(4, 'Drinking Challenge', '2020-06-07','2020-06-09', 'Beer Drinking Competition','Gastown',NULL, NULL );
Let's not allow an event to not have an organizer.

2020-04-06 04:28 UTC, Bosco28 commented on EventFinder-DDLs.sql
> +	OrganizerContactInfo VARCHAR(200),
Let's make these not null

2020-04-06 04:35 UTC, merged